# Generated by Django 6.1 on 2026-09-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='matter',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matter',
            name='is_collaborative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matter',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
