# Generated by Django 6.1 on 2026-09-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_matter_is_archived_matter_is_collaborative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matter',
            name='opposing_counsels_json',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='matter',
            name='summary_text_json',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
